name: Deploy MultiK8s on AWS EKS
on:
  push:
    branches:
      - master

env:
  SHA: $(git rev-parse HEAD)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.28.0' # default is latest stable
        id: install

      - name: Test
        run: |-
          docker build -t shivisis/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true shivisis/react-test npm test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-1


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: |-
          docker build -t shivisis/multi-client-k8s-gh:latest -t shivisis/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t shivisis/multi-server-k8s-gh:latest -t shivisis/multi-server-k8s-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t shivisis/multi-worker-k8s-gh:latest -t shivisis/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker
  
      - name: Push
        run: |-
          docker push shivisis/multi-client-k8s-gh:latest
          docker push shivisis/multi-server-k8s-gh:latest
          docker push shivisis/multi-worker-k8s-gh:latest

          docker push shivisis/multi-client-k8s-gh:${{ env.SHA }}
          docker push shivisis/multi-server-k8s-gh:${{ env.SHA }}
          docker push shivisis/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Update kube config
        run: |-
          aws eks update-kubeconfig --region eu-west-1 --name latest-aws-k8s
          kubectl describe -n kube-system configmap/aws-auth

      - name: Apply
        run: |-
          kubectl apply -f k8s/client-cluster-ip-service.yaml
          kubectl apply -f k8s/client-deployment.yaml
          kubectl apply -f k8s/server-cluster-ip-service.yaml
          kubectl apply -f k8s/server-deployment.yaml
          kubectl apply -f k8s/ingress-service.yaml
          kubectl apply -f k8s/postgres-cluster-ip-service.yaml
          kubectl apply -f k8s/redis-cluster-ip-service.yaml
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl apply -f k8s/redis-deployment.yaml
          kubectl apply -f k8s/worker-deployment.yaml
          kubectl apply -f k8s/database-persistent-volume-claim.yaml
          kubectl set image deployments/server-deployment server=shivisis/multi-server-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=shivisis/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=shivisis/multi-worker-k8s-gh:${{ env.SHA }}
          

      - name: get deployment
        run: |-
          kubectl get deployments
          kubectl get svc
          kubectl get ns
